name: jupyterlab_practice
channels:
  - conda-forge
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
  - https://repo.anaconda.com/pkgs/msys2
dependencies:
  - bzip2=1.0.8
  - ca-certificates=2025.1.31
  - libffi=3.4.6
  - liblzma=5.6.4
  - libsqlite=3.49.1
  - libzlib=1.3.1
  - openssl=3.4.1
  - pip=25.0.1
  - python=3.10.16
  - setuptools=75.8.2
  - tk=8.6.13
  - tzdata=2025a
  - ucrt=10.0.22621.0
  - vc=14.3
  - vc14_runtime=14.42.34438
  - wheel=0.45.1
